import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// All CSS files to bundle into styles.css (in order)
const cssFiles = [
	'src/styles/view/layout.css',
	'src/styles/view/preview.css',
	'src/styles/settings/settings.css',
	'src/styles/theme-editor.css',
	'src/styles/index.css',
];

function concatCss(outputPath) {
	let combined = '';
	for (const file of cssFiles) {
		try {
			const content = readFileSync(resolve(file), 'utf-8');
			combined += `/* ${file} */\n${content}\n`;
		} catch (e) {
			console.warn(`Warning: could not read ${file}:`, e.message);
		}
	}
	// Strip @import lines from index.css since we already inlined the files above
	combined = combined.replace(/@import\s+url\([^)]+\);\s*\n/g, '');
	writeFileSync(outputPath, combined);
	console.log('Bundled CSS to', outputPath);
}

const options = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/plugin.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: false,
	treeShaking: true,
	minify: prod,
	outfile: 'main.js',
	loader: {
		'.css': 'text',
	},
	metafile: false,
};

const footer = {
	js: 'module.exports = module.exports && module.exports.default || module.exports;',
};

if (prod) {
	try {
		await esbuild.build({ ...options, footer });
		concatCss('styles.css');
	} catch (e) {
		console.error(e);
		process.exit(1);
	}
} else {
	try {
		const context = await esbuild.context({ ...options, footer });
		await context.watch();
	} catch (e) {
		console.error(e);
		process.exit(1);
	}
}
