export const SAMPLE_ARTICLE_MARKDOWN = [
    '# Markdown 样式全量测试文章',
    '',
    '## 标题',
    '# 一级标题',
    '## 二级标题',
    '### 三级标题',
    '#### 四级标题',
    '##### 五级标题',
    '###### 六级标题',
    '',
    '## 字体',
    '',
    '*斜体文本* ',
    '**粗体文本** ',
    '***粗斜体文本***',
    '~~删除线~~',
    '<u>下划线</u> (使用HTML标签)',
    '==高亮==',
    '链接：[OpenAI](https://openai.com)',
    '',
    '混合格式：~~旧方案~~、==重点提示==、`python test.py`',
    '### 无序列表',
    '- 列表项一',
    '- 列表项二',
    '  - 子列表项',
    '',
    '### 有序列表',
    '1. 第一项',
    '2. 第二项',
    '3. 第三项',
    '',
    '### 引用',
    '',
    '> 这是引用的内容',
    '> 可以有多行',
    '>> 嵌套引用',
    '',
    '### 代码块',
    '',
    '这是 `行内代码`  ',
    '',
    'JavaScript',
    '',
    '```javascript',
    'function resolveBitableClient(api: OpenClawPluginApi, accountId?: string) {',
    '  const normalizedAccountId = accountId?.trim();',
    '  if (normalizedAccountId) {',
    '    if (!api.config) {',
    '      throw new Error("OpenClaw config is missing; cannot resolve account");',
    '    }',
    '    const account = resolveFeishuAccount({ cfg: api.config, accountId: normalizedAccountId });',
    '    if (!account.enabled) {',
    '      throw new Error(`Feishu account "${account.accountId}" is disabled.`);',
    '    }',
    '    if (!account.configured || !account.appId || !account.appSecret) {',
    '      throw new Error(`Feishu account "${account.accountId}" is not configured.`);',
    '    }',
    '    return createFeishuClient(account);',
    '  }',
    '',
    '  const feishuCfg = api.config?.channels?.feishu as FeishuConfig | undefined;',
    '  if (!feishuCfg?.appId || !feishuCfg?.appSecret) {',
    '    throw new Error(`Feishu credentials not configured.`);',
    '  }',
    '  return createFeishuClient(feishuCfg);',
    '}',
    '```',
    '',
    'python',
    '',
    '```python',
    'def publish_article(title: str, account: str) -> str:',
    '    print(f"publishing {title} to account {account}")',
    '    return "ok"',
    '',
    '',
    'if __name__ == "__main__":',
    '    publish_article("Markdown 样式全量测试文章", "B")',
    '    ',
    'if __name__ == "__main__":',
    '    publish_article("Markdown 样式全量测试文章", "B")',
    '```',
    '',
    '### 图片链接',
    '',
    '![](../other/design/pic/image-03-28-114241.jpg)',
    '',
    '### 分割线',
    '',
    '---',
    '分割内容',
    '___',
    '',
    '### 表格',
    '',
    '| 项目  | 目的     | 是否关键 |',
    '| --- | ------ | ---- |',
    '| 标题  | 看层级样式  | 是    |',
    '| 图片  | 看上传替换  | 是    |',
    '| 表格  | 看边框和间距 | 是    |',
    '| 代码块 | 看背景和换行 | 是    |',
    '|     |        |      |',
    '### 任务列表',
    '',
    '- [x] 完成任务',
    '- [ ] 待办任务',
    '',
].join('\n');

